runtime: nodejs12

env_variables:
    DB_NAME: $DB_NAME
    DB_HOST: $DB_HOST
    DB_PORT: ''
    DB_USERNAME: $DB_USERNAME
    DB_PASSWORD: $DB_PASSWORD
    DB_DRIVER: 'mysql'
    DB_SOCKET: $DB_SOCKET
