runtime: nodejs12

env_variables:
    DB_NAME: $DB_NAME
    DB_HOST: $DB_HOST
    DB_PORT: ''
    DB_USERNAME: $DB_USERNAME
    DB_PASSWORD: $DB_PASSWORD
    DB_DRIVER: $DB_DRIVER
    DB_SOCKET: $DB_SOCKET
    JWT_SECRET: $JWT_SECRET
    JWT_ACCESS_TOKEN_EXPIRATION_TIME: $JWT_ACCESS_TOKEN_EXPIRATION_TIME
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: $JWT_REFRESH_TOKEN_EXPIRATION_TIME
    COOKIE_SECRET: $COOKIE_SECRET
    EMAIL_USERNAME: $EMAIL_USERNAME
    EMAIL_PASSWORD: $EMAIL_PASSWORD
    GCS_BUCKET_NAME: $GCS_BUCKET_NAME
    GCP_SA_KEY: $GCP_SA_KEY
