import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialMigration1613148239672 implements MigrationInterface {
    name = 'InitialMigration1613148239672'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `file` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `filename` varchar(255) NOT NULL, `cloudFilename` varchar(255) NOT NULL, `messageId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `message` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `assignmentType` enum ('homework', 'classwork', 'exam') NULL, `data` varchar(255) NULL, `messageType` enum ('assignment', 'message') NOT NULL, `status` enum ('created', 'published') NOT NULL DEFAULT 'created', `assignmentDueDate` datetime NULL, `fromUserId` varchar(36) NULL, `subjectId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `firstName` varchar(50) NOT NULL, `middleName` varchar(50) NOT NULL, `lastName` varchar(50) NOT NULL, `email` varchar(70) NOT NULL, `password` text NOT NULL, `role` enum ('admin', 'parent', 'student', 'teacher', 'viewer') NOT NULL DEFAULT 'viewer', `registerToken` varchar(255) NULL, `status` enum ('active', 'inactive', 'blocked', 'unverified') NOT NULL DEFAULT 'unverified', `institutionId` varchar(36) NULL, UNIQUE INDEX `IDX_e12875dfb3b1d92d7d7c5377e2` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `student_grade` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `message` varchar(255) NOT NULL, `type` enum ('year', 'turm_1', 'turm_2', 'ongoing') NOT NULL DEFAULT 'ongoing', `grade` int NOT NULL, `gradeWithWords` enum ('0', '1', '2', '3', '4') NOT NULL DEFAULT '4', `fromUserId` varchar(36) NULL, `studentId` varchar(36) NULL, `subjectId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `parent` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` varchar(36) NULL, UNIQUE INDEX `REL_a51bd21a6e90dbe656ad65cab8` (`userId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `student` (`id` varchar(36) NOT NULL, `startDate` date NULL, `prevEducation` text NOT NULL DEFAULT 'none', `token` varchar(10) NOT NULL DEFAULT '', `recordMessage` varchar(255) NULL, `userId` varchar(36) NULL, `classId` varchar(36) NULL, UNIQUE INDEX `REL_b35463776b4a11a3df3c30d920` (`userId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `student_dossier` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `message` varchar(255) NOT NULL, `fromUserId` varchar(36) NULL, `studentId` varchar(36) NULL, `subjectId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `teacher` (`id` varchar(36) NOT NULL, `education` varchar(255) NULL, `yearsExperience` tinyint NULL, `contractType` enum ('part_time', 'full_time') NULL, `token` varchar(10) NOT NULL DEFAULT '', `userId` varchar(36) NULL, UNIQUE INDEX `REL_4f596730e16ee49d9b081b5d8e` (`userId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `subject` (`id` varchar(36) NOT NULL, `startYear` year NOT NULL, `endYear` year NOT NULL, `name` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `institutionId` varchar(36) NULL, `classId` varchar(36) NULL, `messagesId` varchar(36) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `schedule` (`id` varchar(36) NOT NULL, `startTime` datetime NOT NULL, `endTime` datetime NOT NULL, `day` enum ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday') NOT NULL, `room` varchar(255) NOT NULL, `subjectId` varchar(36) NULL, `classId` varchar(36) NULL, `institutionId` varchar(36) NULL, UNIQUE INDEX `IDX_0d58136878eacf57c2f2cf4012` (`institutionId`, `day`, `subjectId`, `classId`, `startTime`, `endTime`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `institution` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `type` enum ('natural_mathematical', 'technological', 'linguistical', 'mathematical', 'humanitarian', 'art', 'su', 'ou') NOT NULL, `educationalStage` enum ('elementary', 'primary', 'united', 'high') NOT NULL, `alias` varchar(255) NOT NULL, UNIQUE INDEX `IDX_d218ad3566afa9e396f184fd7d` (`name`), UNIQUE INDEX `IDX_43c747addb41aeac8b1da0c58d` (`email`), UNIQUE INDEX `IDX_899ffe9da666367e93f96ee4ee` (`alias`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `class` (`id` varchar(36) NOT NULL, `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `startYear` year NOT NULL, `endYear` year NOT NULL, `totalStudentCount` tinyint NOT NULL, `letter` varchar(1) NOT NULL, `number` tinyint NOT NULL, `token` varchar(10) NOT NULL DEFAULT '', `tokenStatus` enum ('0', '1') NOT NULL DEFAULT '0', `institutionId` varchar(36) NULL, `teacherId` varchar(36) NULL, UNIQUE INDEX `IDX_a996c5bc6b48355f9994fdad34` (`letter`, `number`), UNIQUE INDEX `REL_d3e7278501fe8c5e8cf2cf74be` (`teacherId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `message_toUsers` (`message` varchar(36) NOT NULL, `user` varchar(36) NOT NULL, INDEX `IDX_0aad461e5905079b03c8a59378` (`message`), INDEX `IDX_23dae1a3c64a2397705cf6514c` (`user`), PRIMARY KEY (`message`, `user`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `message_toClass` (`message` varchar(36) NOT NULL, `class` varchar(36) NOT NULL, INDEX `IDX_a92b3cfceb8305fc25551fddcf` (`message`), INDEX `IDX_2b0466a321422f71c266d23669` (`class`), PRIMARY KEY (`message`, `class`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `parent_student` (`parent` varchar(36) NOT NULL, `student` varchar(36) NOT NULL, INDEX `IDX_29075d4c562cb3f9387bfa018c` (`parent`), INDEX `IDX_a6e2338394f8824bb2542d53fe` (`student`), PRIMARY KEY (`parent`, `student`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `student_record_files` (`student` varchar(36) NOT NULL, `file` varchar(36) NOT NULL, INDEX `IDX_493edd9a7e5d7ae118d961383c` (`student`), INDEX `IDX_9e462245c47455641c6685cdcf` (`file`), PRIMARY KEY (`student`, `file`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `student_dossier_files` (`dossier` varchar(36) NOT NULL, `file` varchar(36) NOT NULL, INDEX `IDX_f9a1fced041906c790d7fdabba` (`dossier`), INDEX `IDX_ddefaa3b16ae92bad9c2078723` (`file`), PRIMARY KEY (`dossier`, `file`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `teacher_subject` (`subjects` varchar(36) NOT NULL, `teachers` varchar(36) NOT NULL, INDEX `IDX_d3cc8020891fc8cdc8c8307b8c` (`subjects`), INDEX `IDX_0b4ee467ff4113a8aa2517591f` (`teachers`), PRIMARY KEY (`subjects`, `teachers`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `schedule_teacher` (`schedule` varchar(36) NOT NULL, `teacher` varchar(36) NOT NULL, INDEX `IDX_55c95fa0767b1b6636eccaf6eb` (`schedule`), INDEX `IDX_6f2d9eaac5fa05e1f52569eac5` (`teacher`), PRIMARY KEY (`schedule`, `teacher`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `file` ADD CONSTRAINT `FK_a78a68c3f577a485dd4c741909f` FOREIGN KEY (`messageId`) REFERENCES `message`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message` ADD CONSTRAINT `FK_c59262513a3006fd8f58bb4b7c2` FOREIGN KEY (`fromUserId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message` ADD CONSTRAINT `FK_90f162a0d728ff62e18f23646a2` FOREIGN KEY (`subjectId`) REFERENCES `subject`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_ca0de218397aed2409d865d1580` FOREIGN KEY (`institutionId`) REFERENCES `institution`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_grade` ADD CONSTRAINT `FK_bb2a78057d1056a69a223be64f1` FOREIGN KEY (`fromUserId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_grade` ADD CONSTRAINT `FK_2bc4f1801ff5bd70b8a799626ae` FOREIGN KEY (`studentId`) REFERENCES `student`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_grade` ADD CONSTRAINT `FK_68759787c8e6a1a18d22a2b20d8` FOREIGN KEY (`subjectId`) REFERENCES `subject`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `parent` ADD CONSTRAINT `FK_a51bd21a6e90dbe656ad65cab89` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student` ADD CONSTRAINT `FK_b35463776b4a11a3df3c30d920a` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student` ADD CONSTRAINT `FK_bd5c8f2ef67394162384a484ba1` FOREIGN KEY (`classId`) REFERENCES `class`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_dossier` ADD CONSTRAINT `FK_618ab26bd69141bfb3c449e9be8` FOREIGN KEY (`fromUserId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_dossier` ADD CONSTRAINT `FK_17501ddbda8ce8f3163a8f5e5b4` FOREIGN KEY (`studentId`) REFERENCES `student`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_dossier` ADD CONSTRAINT `FK_9852b2043d8111cb5d12a095d11` FOREIGN KEY (`subjectId`) REFERENCES `subject`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `teacher` ADD CONSTRAINT `FK_4f596730e16ee49d9b081b5d8e5` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `subject` ADD CONSTRAINT `FK_6ce29d082752b69b91f64c4e65d` FOREIGN KEY (`institutionId`) REFERENCES `institution`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `subject` ADD CONSTRAINT `FK_bd8702647b256adaa5bb5321565` FOREIGN KEY (`classId`) REFERENCES `class`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `subject` ADD CONSTRAINT `FK_8619e4246b4f695fda4c971a500` FOREIGN KEY (`messagesId`) REFERENCES `message`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `schedule` ADD CONSTRAINT `FK_9fa71efc605659e54dec60bf17e` FOREIGN KEY (`subjectId`) REFERENCES `subject`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `schedule` ADD CONSTRAINT `FK_08aac4a7aad6819197a8ba8f3e8` FOREIGN KEY (`classId`) REFERENCES `class`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `schedule` ADD CONSTRAINT `FK_a6d06452061e23ac52553245b46` FOREIGN KEY (`institutionId`) REFERENCES `institution`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `class` ADD CONSTRAINT `FK_dfd2f9066e412257415d2376c63` FOREIGN KEY (`institutionId`) REFERENCES `institution`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `class` ADD CONSTRAINT `FK_d3e7278501fe8c5e8cf2cf74be7` FOREIGN KEY (`teacherId`) REFERENCES `teacher`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message_toUsers` ADD CONSTRAINT `FK_0aad461e5905079b03c8a593782` FOREIGN KEY (`message`) REFERENCES `message`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message_toUsers` ADD CONSTRAINT `FK_23dae1a3c64a2397705cf6514c0` FOREIGN KEY (`user`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message_toClass` ADD CONSTRAINT `FK_a92b3cfceb8305fc25551fddcf0` FOREIGN KEY (`message`) REFERENCES `message`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `message_toClass` ADD CONSTRAINT `FK_2b0466a321422f71c266d236695` FOREIGN KEY (`class`) REFERENCES `class`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `parent_student` ADD CONSTRAINT `FK_29075d4c562cb3f9387bfa018c9` FOREIGN KEY (`parent`) REFERENCES `parent`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `parent_student` ADD CONSTRAINT `FK_a6e2338394f8824bb2542d53fe6` FOREIGN KEY (`student`) REFERENCES `student`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_record_files` ADD CONSTRAINT `FK_493edd9a7e5d7ae118d961383cf` FOREIGN KEY (`student`) REFERENCES `student`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_record_files` ADD CONSTRAINT `FK_9e462245c47455641c6685cdcfc` FOREIGN KEY (`file`) REFERENCES `file`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_dossier_files` ADD CONSTRAINT `FK_f9a1fced041906c790d7fdabbad` FOREIGN KEY (`dossier`) REFERENCES `student_dossier`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `student_dossier_files` ADD CONSTRAINT `FK_ddefaa3b16ae92bad9c2078723d` FOREIGN KEY (`file`) REFERENCES `file`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `teacher_subject` ADD CONSTRAINT `FK_d3cc8020891fc8cdc8c8307b8cf` FOREIGN KEY (`subjects`) REFERENCES `subject`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `teacher_subject` ADD CONSTRAINT `FK_0b4ee467ff4113a8aa2517591f7` FOREIGN KEY (`teachers`) REFERENCES `teacher`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `schedule_teacher` ADD CONSTRAINT `FK_55c95fa0767b1b6636eccaf6eb1` FOREIGN KEY (`schedule`) REFERENCES `schedule`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `schedule_teacher` ADD CONSTRAINT `FK_6f2d9eaac5fa05e1f52569eac5e` FOREIGN KEY (`teacher`) REFERENCES `teacher`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `schedule_teacher` DROP FOREIGN KEY `FK_6f2d9eaac5fa05e1f52569eac5e`");
        await queryRunner.query("ALTER TABLE `schedule_teacher` DROP FOREIGN KEY `FK_55c95fa0767b1b6636eccaf6eb1`");
        await queryRunner.query("ALTER TABLE `teacher_subject` DROP FOREIGN KEY `FK_0b4ee467ff4113a8aa2517591f7`");
        await queryRunner.query("ALTER TABLE `teacher_subject` DROP FOREIGN KEY `FK_d3cc8020891fc8cdc8c8307b8cf`");
        await queryRunner.query("ALTER TABLE `student_dossier_files` DROP FOREIGN KEY `FK_ddefaa3b16ae92bad9c2078723d`");
        await queryRunner.query("ALTER TABLE `student_dossier_files` DROP FOREIGN KEY `FK_f9a1fced041906c790d7fdabbad`");
        await queryRunner.query("ALTER TABLE `student_record_files` DROP FOREIGN KEY `FK_9e462245c47455641c6685cdcfc`");
        await queryRunner.query("ALTER TABLE `student_record_files` DROP FOREIGN KEY `FK_493edd9a7e5d7ae118d961383cf`");
        await queryRunner.query("ALTER TABLE `parent_student` DROP FOREIGN KEY `FK_a6e2338394f8824bb2542d53fe6`");
        await queryRunner.query("ALTER TABLE `parent_student` DROP FOREIGN KEY `FK_29075d4c562cb3f9387bfa018c9`");
        await queryRunner.query("ALTER TABLE `message_toClass` DROP FOREIGN KEY `FK_2b0466a321422f71c266d236695`");
        await queryRunner.query("ALTER TABLE `message_toClass` DROP FOREIGN KEY `FK_a92b3cfceb8305fc25551fddcf0`");
        await queryRunner.query("ALTER TABLE `message_toUsers` DROP FOREIGN KEY `FK_23dae1a3c64a2397705cf6514c0`");
        await queryRunner.query("ALTER TABLE `message_toUsers` DROP FOREIGN KEY `FK_0aad461e5905079b03c8a593782`");
        await queryRunner.query("ALTER TABLE `class` DROP FOREIGN KEY `FK_d3e7278501fe8c5e8cf2cf74be7`");
        await queryRunner.query("ALTER TABLE `class` DROP FOREIGN KEY `FK_dfd2f9066e412257415d2376c63`");
        await queryRunner.query("ALTER TABLE `schedule` DROP FOREIGN KEY `FK_a6d06452061e23ac52553245b46`");
        await queryRunner.query("ALTER TABLE `schedule` DROP FOREIGN KEY `FK_08aac4a7aad6819197a8ba8f3e8`");
        await queryRunner.query("ALTER TABLE `schedule` DROP FOREIGN KEY `FK_9fa71efc605659e54dec60bf17e`");
        await queryRunner.query("ALTER TABLE `subject` DROP FOREIGN KEY `FK_8619e4246b4f695fda4c971a500`");
        await queryRunner.query("ALTER TABLE `subject` DROP FOREIGN KEY `FK_bd8702647b256adaa5bb5321565`");
        await queryRunner.query("ALTER TABLE `subject` DROP FOREIGN KEY `FK_6ce29d082752b69b91f64c4e65d`");
        await queryRunner.query("ALTER TABLE `teacher` DROP FOREIGN KEY `FK_4f596730e16ee49d9b081b5d8e5`");
        await queryRunner.query("ALTER TABLE `student_dossier` DROP FOREIGN KEY `FK_9852b2043d8111cb5d12a095d11`");
        await queryRunner.query("ALTER TABLE `student_dossier` DROP FOREIGN KEY `FK_17501ddbda8ce8f3163a8f5e5b4`");
        await queryRunner.query("ALTER TABLE `student_dossier` DROP FOREIGN KEY `FK_618ab26bd69141bfb3c449e9be8`");
        await queryRunner.query("ALTER TABLE `student` DROP FOREIGN KEY `FK_bd5c8f2ef67394162384a484ba1`");
        await queryRunner.query("ALTER TABLE `student` DROP FOREIGN KEY `FK_b35463776b4a11a3df3c30d920a`");
        await queryRunner.query("ALTER TABLE `parent` DROP FOREIGN KEY `FK_a51bd21a6e90dbe656ad65cab89`");
        await queryRunner.query("ALTER TABLE `student_grade` DROP FOREIGN KEY `FK_68759787c8e6a1a18d22a2b20d8`");
        await queryRunner.query("ALTER TABLE `student_grade` DROP FOREIGN KEY `FK_2bc4f1801ff5bd70b8a799626ae`");
        await queryRunner.query("ALTER TABLE `student_grade` DROP FOREIGN KEY `FK_bb2a78057d1056a69a223be64f1`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_ca0de218397aed2409d865d1580`");
        await queryRunner.query("ALTER TABLE `message` DROP FOREIGN KEY `FK_90f162a0d728ff62e18f23646a2`");
        await queryRunner.query("ALTER TABLE `message` DROP FOREIGN KEY `FK_c59262513a3006fd8f58bb4b7c2`");
        await queryRunner.query("ALTER TABLE `file` DROP FOREIGN KEY `FK_a78a68c3f577a485dd4c741909f`");
        await queryRunner.query("DROP INDEX `IDX_6f2d9eaac5fa05e1f52569eac5` ON `schedule_teacher`");
        await queryRunner.query("DROP INDEX `IDX_55c95fa0767b1b6636eccaf6eb` ON `schedule_teacher`");
        await queryRunner.query("DROP TABLE `schedule_teacher`");
        await queryRunner.query("DROP INDEX `IDX_0b4ee467ff4113a8aa2517591f` ON `teacher_subject`");
        await queryRunner.query("DROP INDEX `IDX_d3cc8020891fc8cdc8c8307b8c` ON `teacher_subject`");
        await queryRunner.query("DROP TABLE `teacher_subject`");
        await queryRunner.query("DROP INDEX `IDX_ddefaa3b16ae92bad9c2078723` ON `student_dossier_files`");
        await queryRunner.query("DROP INDEX `IDX_f9a1fced041906c790d7fdabba` ON `student_dossier_files`");
        await queryRunner.query("DROP TABLE `student_dossier_files`");
        await queryRunner.query("DROP INDEX `IDX_9e462245c47455641c6685cdcf` ON `student_record_files`");
        await queryRunner.query("DROP INDEX `IDX_493edd9a7e5d7ae118d961383c` ON `student_record_files`");
        await queryRunner.query("DROP TABLE `student_record_files`");
        await queryRunner.query("DROP INDEX `IDX_a6e2338394f8824bb2542d53fe` ON `parent_student`");
        await queryRunner.query("DROP INDEX `IDX_29075d4c562cb3f9387bfa018c` ON `parent_student`");
        await queryRunner.query("DROP TABLE `parent_student`");
        await queryRunner.query("DROP INDEX `IDX_2b0466a321422f71c266d23669` ON `message_toClass`");
        await queryRunner.query("DROP INDEX `IDX_a92b3cfceb8305fc25551fddcf` ON `message_toClass`");
        await queryRunner.query("DROP TABLE `message_toClass`");
        await queryRunner.query("DROP INDEX `IDX_23dae1a3c64a2397705cf6514c` ON `message_toUsers`");
        await queryRunner.query("DROP INDEX `IDX_0aad461e5905079b03c8a59378` ON `message_toUsers`");
        await queryRunner.query("DROP TABLE `message_toUsers`");
        await queryRunner.query("DROP INDEX `REL_d3e7278501fe8c5e8cf2cf74be` ON `class`");
        await queryRunner.query("DROP INDEX `IDX_a996c5bc6b48355f9994fdad34` ON `class`");
        await queryRunner.query("DROP TABLE `class`");
        await queryRunner.query("DROP INDEX `IDX_899ffe9da666367e93f96ee4ee` ON `institution`");
        await queryRunner.query("DROP INDEX `IDX_43c747addb41aeac8b1da0c58d` ON `institution`");
        await queryRunner.query("DROP INDEX `IDX_d218ad3566afa9e396f184fd7d` ON `institution`");
        await queryRunner.query("DROP TABLE `institution`");
        await queryRunner.query("DROP INDEX `IDX_0d58136878eacf57c2f2cf4012` ON `schedule`");
        await queryRunner.query("DROP TABLE `schedule`");
        await queryRunner.query("DROP TABLE `subject`");
        await queryRunner.query("DROP INDEX `REL_4f596730e16ee49d9b081b5d8e` ON `teacher`");
        await queryRunner.query("DROP TABLE `teacher`");
        await queryRunner.query("DROP TABLE `student_dossier`");
        await queryRunner.query("DROP INDEX `REL_b35463776b4a11a3df3c30d920` ON `student`");
        await queryRunner.query("DROP TABLE `student`");
        await queryRunner.query("DROP INDEX `REL_a51bd21a6e90dbe656ad65cab8` ON `parent`");
        await queryRunner.query("DROP TABLE `parent`");
        await queryRunner.query("DROP TABLE `student_grade`");
        await queryRunner.query("DROP INDEX `IDX_e12875dfb3b1d92d7d7c5377e2` ON `user`");
        await queryRunner.query("DROP TABLE `user`");
        await queryRunner.query("DROP TABLE `message`");
        await queryRunner.query("DROP TABLE `file`");
    }

}
