name: Google App Engine Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@master
              with:
                  node-version: 12
            - run: npm install
            - run: npm run build
            - name: Compile ENV
              uses: ikuanyshbekov/app-yaml-env-compiler@master
              env:
                  DB_NAME: ${{ secrets.DB_NAME }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_DRIVER: ${{ secrets.DB_DRIVER }}
                  DB_SOCKET: ${{ secrets.DB_SOCKET }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }}
                  JWT_REFRESH_TOKEN_EXPIRATION_TIME: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_TIME }}
                  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
                  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            - name: Deploy to GAE
              uses: google-github-actions/deploy-appengine@main
              with:
                  credentials: ${{ secrets.GCP_SA_KEY }}
                  project_id: heggyo
